name: 'Check commit status'
inputs:
  statusName:
    description: 'Name of the commit status to check'
    required: true
  githubToken:
    description: 'GitHub token'
    required: true
  commitRef:
    description: 'Commit ref to check'
    required: true
    

runs:
  using: "composite"
  steps:
    - name: Wait for commit status
      uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
      id: wait
      with:
        token: ${{ inputs.githubToken}}
        statusName: ${{ inputs.statusName }}
        timeoutSeconds: "300"
        ref: ${{ inputs.commitRef }}
    - name: Check if commit status is not success
      shell: bash
      if: steps.wait.outputs.state != 'success'
      run: |
        echo '${{ inputs.statusName }} failed.'
        exit 1