apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}-runtime-configuration
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
data:
{{- with .Values.runtimeConfiguration }}
{{ tpl . $ | indent 6 }}
{{- end }}