apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "kyma-env-broker.name" . }}
    release: {{ .Values.namePrefix }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "get"]
  - apiGroups: [ "operator.kyma-project.io" ]
    resources: [ "kymas" ]
    verbs: [ "create", "update", "get", "list","delete" ]
  - apiGroups: [ "infrastructuremanager.kyma-project.io" ]
    resources: [ "gardenerclusters" ]
    verbs: [ "create", "update", "get", "list", "delete" ]
  - apiGroups: [ "infrastructuremanager.kyma-project.io" ]
    resources: [ "runtimes" ]
    verbs: [ "create", "update", "get", "list", "delete" ]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "kyma-env-broker.name" . }}
    release: {{ .Values.namePrefix }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.kyma_environment_broker.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kyma-env-broker.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.kyma_environment_broker.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml .Values.serviceAccount.annotations) . | indent 4 }}
{{- end }}
