apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - name: postgres-default-port
    protocol: TCP
    port: 5432
    targetPort: postgres-port