name: Run KEB chart install tests

on:
  pull_request:
    branches: [ main ]

jobs:
  run-install-keb-chart-tests:
    uses: "./.github/workflows/run-keb-chart-install-tests-reusable.yaml"
    if: ${{ !github.event.pull_request.draft }}
    with:
      last-k3s-versions: 3
      release: "false"
      version: ${{ github.event.pull_request.number }}